# Generated by Django 3.2 on 2021-04-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.URLField(max_length=70, verbose_name='Изобрание')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тесто')),
                ('cost', models.SmallIntegerField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.URLField(max_length=70, verbose_name='Изобрание')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Ингредиент')),
                ('cost', models.SmallIntegerField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=25, verbose_name='Размер')),
                ('cost', models.SmallIntegerField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('image', models.URLField(max_length=70, verbose_name='Изображение')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('dough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_pizza.dough')),
                ('ingredients', models.ManyToManyField(to='api_pizza.Ingredient')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_pizza.size')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.URLField(max_length=70, verbose_name='Изображение')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('dough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_pizza.dough')),
                ('ingredients', models.ManyToManyField(to='api_pizza.Ingredient')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_pizza.size')),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
    ]
