# Generated by Django 3.2 on 2021-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pizza', '0003_auto_20210410_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='count',
            field=models.SmallIntegerField(default=1, verbose_name='Количество порций'),
        ),
    ]
