# Generated by Django 3.2 on 2021-04-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pizza', '0004_ingredient_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='additionalIngredients',
            field=models.ManyToManyField(null=True, related_name='addIngredients', to='api_pizza.Ingredient'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='api_pizza.Ingredient'),
        ),
    ]
