# Generated by Django 3.2 on 2021-04-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_pizza', '0005_auto_20210410_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='additionalIngredients',
            field=models.ManyToManyField(related_name='addIngredients', to='api_pizza.Ingredient'),
        ),
        migrations.CreateModel(
            name='IntermediateCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.URLField(max_length=150, verbose_name='Изображение')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('sold', models.BooleanField(default=False)),
                ('additionalIngredients', models.ManyToManyField(related_name='intermediate_addIngredients', to='api_pizza.Ingredient')),
                ('dough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_pizza.dough')),
                ('ingredients', models.ManyToManyField(related_name='intermediate_ingredients', to='api_pizza.Ingredient')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_pizza.size')),
            ],
        ),
    ]
