# Generated by Django 3.2 on 2021-04-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_pizza', '0008_auto_20210414_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('client_phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Емайл')),
                ('client_address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('order_commentary', models.TextField(verbose_name='Комментарий')),
                ('order_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_pizza.cart')),
            ],
        ),
    ]
