# Generated by Django 3.2 on 2021-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pizza', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_products',
        ),
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(to='api_pizza.Cart'),
        ),
    ]
