# Generated by Django 3.2 on 2021-04-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pizza', '0010_auto_20210416_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.SmallIntegerField(default=0),
        ),
    ]
