# Generated by Django 3.2 on 2021-04-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pizza', '0011_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='additionalIngredients',
            field=models.ManyToManyField(related_name='addIngredients', to='api_pizza.Ingredient'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='api_pizza.Ingredient'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.URLField(max_length=300, verbose_name='Изобрание'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.URLField(max_length=300, verbose_name='Изобрание'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.URLField(max_length=300, verbose_name='Изображение'),
        ),
    ]
