# Generated by Django 3.2 on 2021-04-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pizza', '0013_auto_20210422_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.BooleanField(default=False),
        ),
    ]
